"Traceback (most recent call last):
  File ""C:\Users\maike_000\Documents\Codigos\JAVA\Problema de la cena de los filósofos\so_filosofos\filosofos.py"", line 132, in <module>
    main()
  File ""C:\Users\maike_000\Documents\Codigos\JAVA\Problema de la cena de los filósofos\so_filosofos\filosofos.py"", line 107, in main
    f.start() #ES EQUIVALENTE A RUN()
  File ""c:\users\maike_000\appdata\local\programs\python\python39-32\lib\threading.py"", line 874, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
"
